default_language_version:
  python: python3

exclude: '.*svg$|.*ipynb$|.*md$|.*png$|.*odg|.*tex'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - name: Don't commit on `main` branch
        id: no-commit-to-branch
        args:
          - --branch
          - main
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-docstring-first
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: forbid-new-submodules

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.20.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [ black==23.3.0 ]
        args: ["-l", "90"]
        exclude: ^.github/


  - repo: https://github.com/jsh9/pydoclint
    rev: 0.8.3
    hooks:
      - id: pydoclint
        exclude: ^docs/ |  ^setup\.py$ | ^tests/ |

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff-check
        args: ["--fix", "--output-format=full"]
        files: ^(src|tests|examples)/
        verbose: true
      - id: ruff-format
        files: ^(src|tests|examples)/
        verbose: true

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=additionals,alle,alot,bund,currenty,datas,farenheit,falsy,fo,haa,hass,iif,incomfort,ines,ist,nam,nd,pres,pullrequests,resset,rime,ser,serie,te,technik,ue,unsecure,withing,zar,crate
          - --skip="./.*,*.csv,*.json,*.ambr"
          - --quiet-level=2
        exclude_types: [ csv, json, svg ]
        exclude: ^tests/|generated/
